# Generated by Django 4.0.2 on 2022-02-10 12:19

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(default=web.models.gen_license, editable=False, max_length=6, verbose_name='licenss key'),
        ),
    ]
