# Generated by Django 3.2.3 on 2022-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact_alter_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='mac',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='license',
            name='used',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
