# Generated by Django 3.2.3 on 2022-02-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220212_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='key_info',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='license',
            name='mac',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='license',
            name='used',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
