# Generated by Django 3.2.3 on 2022-03-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220225_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='key_help_link',
            field=models.URLField(blank=True),
        ),
    ]
