# Generated by Django 3.2.3 on 2022-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contact_key_help_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
            ],
        ),
    ]
