# Generated by Django 3.2.3 on 2022-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_messagebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
    ]
